// Folk Atlas: folktales as wisps of light over a globe that unrolls into a flat map.
// data/map.json and data/tales/<id>.json are generated by scripts/build-data.js from the
// trilogy Annotated Folktales; data/world.json holds Natural Earth countries (scripts/build-world.js).

import {
  geoDistance,
  geoEquirectangularRaw,
  geoGraticule10,
  geoOrthographicRaw,
  geoPath,
  geoProjectionMutator,
} from 'd3-geo';
import { feature } from 'topojson-client';
import { indexTale, searchTales } from './lib/search.js';
import { angle, random, rankBySpread, smoothstep, sunflower } from './lib/wisps.js';

(async function () {
  const $ = (sel) => document.querySelector(sel);
  const RAD = Math.PI / 180;
  const ZMAX = 4.5;
  // Wisps show when they are at least this many pixels from every brighter wisp.
  const WISP_SPACING = 26;
  const KIN_SHOWN = 9;
  const OTHERS_SHOWN = 4;
  const reduceMotion = matchMedia('(prefers-reduced-motion: reduce)').matches;

  const clamp = (x, a, b) => Math.max(a, Math.min(b, x));
  const ease = (t) => (t < 0.5 ? 2 * t * t : 1 - Math.pow(-2 * t + 2, 2) / 2);
  const wrap = (d) => ((((d + 180) % 360) + 360) % 360) - 180;
  const el = (tag, cls, text) => {
    const e = document.createElement(tag);
    if (cls) e.className = cls;
    if (text != null) e.textContent = text;
    return e;
  };
  const SVG = 'http://www.w3.org/2000/svg';
  const svgEl = (tag, cls) => {
    const e = document.createElementNS(SVG, tag);
    if (cls) e.setAttribute('class', cls);
    return e;
  };

  const worldEl = $('#world');
  const panel = $('#panel');
  const loading = $('#loading');

  drawSky();
  window.addEventListener('resize', drawSky);

  const json = (url) =>
    fetch(url).then((r) => {
      if (!r.ok) throw new Error(`${url}: ${r.status}`);
      return r.json();
    });
  let data, world;
  try {
    [data, world] = await Promise.all([json('data/map.json'), json('data/world.json')]);
  } catch (err) {
    console.error(err);
    loading.textContent = 'The wisps could not be gathered. Try reloading.';
    return;
  }

  // ---------- Tales, places and their kin ----------

  const typeInfo = (atu) => {
    const [name = '', famIdx = -1] = data.types[atu] ?? [];
    const [family = '', kind = -1] = data.families[famIdx] ?? [];
    return { typeName: name, famIdx, family, kind: data.kinds[kind] ?? '' };
  };

  const places = data.places.map((p) => ({ ...p, tales: [] }));
  const placeById = new Map(places.map((p) => [p.id, p]));
  const tales = [];
  for (const [i, p] of data.places.entries()) {
    for (const [id, title, atu, excerpt] of p.tales) {
      const tale = { id, title, atu, excerpt, place: places[i], ...typeInfo(atu) };
      indexTale(tale, tale.typeName, `atu ${atu}`, p.name, tale.family, tale.kind, excerpt);
      places[i].tales.push(tale);
      tales.push(tale);
    }
  }
  const taleById = new Map(tales.map((t) => [t.id, t]));

  // key -> place -> tales of that key there
  const group = (keyOf) => {
    const map = new Map();
    for (const t of tales) {
      const key = keyOf(t);
      if (!map.has(key)) map.set(key, new Map());
      const byPlace = map.get(key);
      if (!byPlace.has(t.place)) byPlace.set(t.place, []);
      byPlace.get(t.place).push(t);
    }
    return map;
  };
  const byType = group((t) => t.atu);
  const byFamily = group((t) => t.famIdx);
  const kinOf = (tale, mode) => {
    const byPlace = (mode === 'type' ? byType.get(tale.atu) : byFamily.get(tale.famIdx)) ?? new Map();
    return [...byPlace]
      .filter(([place]) => place !== tale.place)
      .sort((a, b) => b[1].length - a[1].length || a[0].name.localeCompare(b[0].name))
      .map(([place, list]) => ({ place, tales: list }));
  };

  // ---------- The map ----------

  const countries = feature(world, world.objects.countries).features;
  const land = feature(world, world.objects.land);
  const graticule = geoGraticule10();
  const countryPaths = new Map();
  const countriesEl = $('#countries');
  for (const f of countries) {
    const path = svgEl('path', 'ct');
    countriesEl.append(path);
    countryPaths.set(f, path);
  }
  const countryEls = new Map(countries.map((f) => [f.properties.name, countryPaths.get(f)]));

  // Blends an orthographic globe (a = 0) into an equirectangular map (a = 1).
  const projectionAt = geoProjectionMutator((a) => (x, y) => {
    const p0 = geoOrthographicRaw(x, y);
    const p1 = geoEquirectangularRaw(x, y);
    return [p0[0] + a * (p1[0] - p0[0]), p0[1] + a * (p1[1] - p0[1])];
  });

  // z: 0 is the globe, 1 the flat world map, above 1 zoomed into the map.
  const v = { z: 0, lon: 20, lat: 22 };
  let anim = null;
  let drag = null;
  let pinch = null;
  let idleSince = 0;
  const t0 = performance.now();

  // Where the globe sits: centred in the space the header, controls and panel leave free.
  let target = null;
  let lay = null;
  function measure() {
    const W = innerWidth;
    const H = innerHeight;
    let x0 = 0;
    let x1 = W;
    let y0 = Math.max(56, $('.top').getBoundingClientRect().bottom - 8);
    let y1 = H;
    const controls = $('.controls').getBoundingClientRect();
    if (controls.top < H * 0.3) y0 = Math.max(y0, controls.bottom + 16);
    if (!panel.hidden) {
      const r = panel.getBoundingClientRect();
      if (r.left > W * 0.45) x1 = r.left + parseFloat(getComputedStyle(panel).right);
      else y1 = r.top;
    }
    const k = clamp(Math.min((x1 - x0) / 1056, (y1 - y0) / 828), 0.25, 1.8);
    const cx = (x0 + x1) / 2;
    target = { W, H, cx, cy: (y0 + y1) / 2, sg: 280 * k, sf: 160 * k, shift: (W / 2 - cx) * 0.58 };
    if (!lay) lay = { ...target };
  }
  function stepLayout() {
    let changed = false;
    for (const key of ['cx', 'cy', 'sg', 'sf', 'shift']) {
      const d = target[key] - lay[key];
      if (d === 0) continue;
      lay[key] = Math.abs(d) < 0.3 ? target[key] : lay[key] + d * 0.18;
      changed = true;
    }
    lay.W = target.W;
    lay.H = target.H;
    return changed;
  }

  function view() {
    const z = clamp(v.z, 0, ZMAX);
    const a = ease(clamp(z, 0, 1));
    const fade = ease(clamp((z - 1) / 0.7, 0, 1));
    const s = z <= 1 ? lay.sg + (lay.sf - lay.sg) * a : lay.sf * Math.pow(2, z - 1);
    // Zoomed in, keep the map's edges beyond the edges of the screen.
    const maxN = 90 - lay.cy / s / RAD;
    const maxS = 90 - (lay.H - lay.cy) / s / RAD;
    const latF = -maxS <= maxN ? clamp(v.lat, -maxS, maxN) : (maxN - maxS) / 2;
    return {
      z,
      a,
      s,
      fade,
      cx: lay.cx + lay.shift * fade,
      cy: lay.cy,
      lon: v.lon,
      latF,
      rotLat: clamp(v.lat, -70, 70) * (1 - a),
      clip: a < 0.999 ? 90 + 89.5 * a : null,
    };
  }

  function project(vw) {
    const p = projectionAt(vw.a);
    p.rotate([-vw.lon, -vw.rotLat])
      .scale(vw.s)
      .translate([vw.cx, vw.cy + vw.latF * RAD * vw.s * vw.a])
      .clipAngle(vw.clip)
      .precision(0.6);
    return p;
  }

  // The astrolabe ring around the globe; it grows away as the map unrolls.
  function frame(vw) {
    const m = 1 + 3 * vw.fade;
    const rx = vw.s * (1.18 + (2.95 - 1.18) * vw.a) * m;
    const ry = vw.s * (1.18 + (1.72 - 1.18) * vw.a) * m;
    const rx2 = rx + 18;
    const ry2 = ry + 18;
    const { cx, cy } = vw;
    let ticks = '';
    let stars = '';
    for (let deg = 0; deg < 360; deg += 2) {
      const th = deg * RAD;
      const c = Math.cos(th);
      const sn = Math.sin(th);
      const L = deg % 30 === 0 ? 15 : deg % 10 === 0 ? 9 : 4;
      ticks += `M${(cx + rx2 * c).toFixed(1)} ${(cy + ry2 * sn).toFixed(1)}L${(cx + (rx2 - L) * c).toFixed(1)} ${(cy + (ry2 - L) * sn).toFixed(1)}`;
      if (deg % 30 === 15) {
        const px = cx + (rx + 9) * c;
        const py = cy + (ry + 9) * sn;
        const k = 3.2;
        const q = 0.8;
        const pts = [[0, -k], [q, -q], [k, 0], [q, q], [0, k], [-q, q], [-k, 0], [-q, -q]];
        stars += pts.map(([dx, dy], i) => `${i ? 'L' : 'M'}${(px + dx).toFixed(1)} ${(py + dy).toFixed(1)}`).join('') + 'Z';
      }
    }
    return { cx, cy, rx, ry, rx2, ry2, ticks, stars, op: 1 - vw.fade };
  }

  const attrs = (node, values) => {
    for (const [k, val] of Object.entries(values)) node.setAttribute(k, val);
  };

  let fr = null;
  function drawMap(vw, p) {
    const path = geoPath(p);
    const sphere = path({ type: 'Sphere' }) ?? '';
    $('#sphere').setAttribute('d', sphere);
    $('#rim').setAttribute('d', sphere);
    $('#rim').style.opacity = (1 - vw.a).toFixed(3);
    $('#graticule').setAttribute('d', path(graticule) ?? '');
    for (const [f, node] of countryPaths) node.setAttribute('d', path(f) ?? '');
    $('#coast').setAttribute('d', path(land) ?? '');
    attrs($('#glow-disc'), { cx: vw.cx, cy: vw.cy, r: vw.s });
    $('#glow-disc').style.opacity = ((1 - vw.a) * 0.55).toFixed(3);

    fr = frame(vw);
    attrs($('#frame-clip'), { cx: fr.cx, cy: fr.cy, rx: fr.rx, ry: fr.ry });
    attrs($('#frame-inner'), { cx: fr.cx, cy: fr.cy, rx: fr.rx, ry: fr.ry });
    attrs($('#frame-outer'), { cx: fr.cx, cy: fr.cy, rx: fr.rx2, ry: fr.ry2 });
    $('#frame-ticks').setAttribute('d', fr.ticks);
    $('#frame-stars').setAttribute('d', fr.stars);
    attrs($('#frame-north'), { x: fr.cx, y: fr.cy - fr.ry2 - 12 });
    attrs($('#frame-south'), { x: fr.cx, y: fr.cy + fr.ry2 + 22 });
    $('#frame').style.opacity = fr.op.toFixed(3);
  }

  // How visible a point is: fades out near the globe's edge.
  const visibility = (vw, lonLat) =>
    vw.clip === null ? 1 : clamp((vw.clip - geoDistance(lonLat, [vw.lon, vw.rotLat]) / RAD) / 5, 0, 1);

  // Constellation: arcs from the chosen tale to a kindred tale in every place that has one.
  const arcsEl = $('#arcs');
  const endsEl = $('#ends');
  function drawArcs(vw, p) {
    const path = geoPath(p);
    const from = [state.sel.lon, state.sel.lat];
    const kin = state.kin;
    while (arcsEl.childElementCount < kin.length) {
      const g = svgEl('g');
      g.append(svgEl('path', 'arcg'), svgEl('path', 'arc'));
      arcsEl.append(g);
      const end = svgEl('circle', 'end');
      end.setAttribute('r', '2.6');
      endsEl.append(end);
    }
    [...arcsEl.children].forEach((g, i) => {
      const k = kin[i];
      g.style.display = k ? '' : 'none';
      endsEl.children[i].style.display = 'none';
      if (!k) return;
      const to = [k.tales[0].lon, k.tales[0].lat];
      const d = path({ type: 'LineString', coordinates: [from, to] }) ?? '';
      g.firstChild.setAttribute('d', d);
      g.lastChild.setAttribute('d', d);
      const vis = visibility(vw, to);
      const xy = p(to);
      if (xy && vis > 0) {
        const end = endsEl.children[i];
        attrs(end, { cx: xy[0].toFixed(1), cy: xy[1].toFixed(1) });
        end.style.display = '';
        end.style.opacity = vis.toFixed(2);
      }
    });
  }

  // ---------- Wisps: every tale is one, shown as zoom makes room ----------

  // Each tale's spot: its place's most widely told tale at the place itself, the others around it.
  for (const place of places) {
    place.tales.sort((a, b) => byType.get(b.atu).size - byType.get(a.atu).size || a.id - b.id);
    sunflower(place.tales.length, place.lat).forEach(([dLon, dLat], i) => {
      place.tales[i].lon = place.lng + dLon;
      place.tales[i].lat = place.lat + dLat;
    });
  }
  const { spacing } = rankBySpread(
    tales.map((t) => [t.lon, t.lat]),
    7,
  );
  for (const [i, tale] of tales.entries()) {
    const rnd = random(tale.id * 7919);
    tale.spacing = spacing[i];
    // Drift a few pixels around its spot, and come and go slowly where the zoom is about to show or hide it.
    tale.drift = { r: 2.5 + rnd() * 3, f: [0, 0, 0, 0].map(() => 0.12 + rnd() * 0.25), ph: [0, 0, 0, 0].map(() => rnd() * Math.PI * 2) };
    tale.tide = { f: (2 * Math.PI) / (25 + rnd() * 35), ph: rnd() * Math.PI * 2 };
  }

  const wispsEl = $('#wisps');
  const wispNodes = new Map(); // tale -> button, made the first time the tale shows
  let forced = new Set(); // the chosen tale and its kin always show

  const wispClass = (tale) => (tale === state.sel ? 'on' : forced.has(tale) ? 'kin' : '');
  function wispNode(tale) {
    let b = wispNodes.get(tale);
    if (b) return b;
    b = el('button', `wisp hid ${wispClass(tale)}`);
    b.hid = true;
    b.type = 'button';
    b.setAttribute('aria-label', `${tale.title}, ${tale.place.name}`);
    const dur = `${(4 + ((tale.id * 1.37) % 3.5)).toFixed(2)}s`;
    const delay = `${(-((tale.id * 1.91) % 7)).toFixed(2)}s`;
    const halo = el('span', 'halo');
    const core = el('span', 'core');
    for (const s of [halo, core]) Object.assign(s.style, { animationDuration: dur, animationDelay: delay });
    b.append(halo, el('span', 'ring'), el('span', 'ray'), el('span', 'ray v'), core, el('span', 'wl', tale.title));
    b.addEventListener('click', () => pick(tale.id));
    wispsEl.append(b);
    wispNodes.set(tale, b);
    return b;
  }
  const hideWisp = (tale) => {
    const b = wispNodes.get(tale);
    if (b && !b.hid) b.classList.add('hid'), (b.hid = true);
  };

  function drawWisps(vw, p, now) {
    const t = reduceMotion ? 0 : (now - t0) / 1000;
    const minSpacing = WISP_SPACING / vw.s; // radians on the ground
    for (const tale of tales) {
      let alpha = 1;
      if (!forced.has(tale)) {
        const tide = 1 + 0.3 * Math.sin(tale.tide.f * t + tale.tide.ph);
        alpha = smoothstep((tale.spacing / (minSpacing * tide) - 1) / 0.6);
      }
      if (alpha <= 0.01) {
        hideWisp(tale);
        continue;
      }
      const { r, f, ph } = tale.drift;
      const k = r / (vw.s * RAD); // pixels -> degrees
      const cl = Math.max(0.3, Math.cos(tale.lat * RAD));
      const lon = tale.lon + (k * (0.65 * Math.sin(f[0] * t + ph[0]) + 0.35 * Math.sin(f[1] * 1.7 * t + ph[1]))) / cl;
      const lat = tale.lat + k * (0.65 * Math.sin(f[2] * t + ph[2]) + 0.35 * Math.sin(f[3] * 1.7 * t + ph[3]));
      let vis = visibility(vw, [lon, lat]);
      const xy = vis > 0 ? p([lon, lat]) : null;
      if (!xy || xy[0] < -30 || xy[0] > lay.W + 30 || xy[1] < -30 || xy[1] > lay.H + 30) vis = 0;
      else {
        const ex = (xy[0] - fr.cx) / fr.rx;
        const ey = (xy[1] - fr.cy) / fr.ry;
        vis = Math.min(vis, clamp((1 - ex * ex - ey * ey) / 0.06, 0, 1));
      }
      if (vis * alpha <= 0.01) {
        hideWisp(tale);
        continue;
      }
      const b = wispNode(tale);
      if (b.hid !== false) b.classList.remove('hid'), (b.hid = false);
      b.style.transform = `translate(${(xy[0] - 22).toFixed(1)}px,${(xy[1] - 22).toFixed(1)}px)`;
      b.style.opacity = (vis * alpha).toFixed(2);
    }
  }

  // ---------- Animation loop ----------

  function flyTo(to, dur = 900) {
    const t = { z: to.z ?? v.z, lon: to.lon ?? v.lon, lat: to.lat ?? v.lat };
    anim = { start: performance.now(), dur, from: { ...v }, to: t, dlon: wrap(t.lon - v.lon) };
  }

  function stepView(now, dt) {
    if (anim) {
      const k = clamp((now - anim.start) / anim.dur, 0, 1);
      const e = ease(k);
      v.z = anim.from.z + (anim.to.z - anim.from.z) * e;
      v.lon = wrap(anim.from.lon + anim.dlon * e);
      v.lat = anim.from.lat + (anim.to.lat - anim.from.lat) * e;
      if (k >= 1) anim = null;
    } else if (!drag && !pinch && !reduceMotion && v.z < 0.4 && now - idleSince > 4000) {
      v.lon = wrap(v.lon + (3.5 * dt) / 1000);
    }
  }

  function clampLat() {
    if (v.z >= 1) v.lat = view().latF;
    else v.lat = clamp(v.lat, -70, 70);
  }

  let mapKey = '';
  let arcsDirty = true;
  let controlsKey = '';
  let prev = performance.now();
  function loop(now) {
    requestAnimationFrame(loop);
    const dt = Math.min(100, now - prev);
    prev = now;
    stepLayout();
    stepView(now, dt);
    const vw = view();
    const p = project(vw);
    const key = [vw.z, v.lon, v.lat, lay.cx, lay.cy, lay.sg, lay.sf].map((n) => n.toFixed(3)).join();
    if (key !== mapKey) {
      mapKey = key;
      drawMap(vw, p);
      arcsDirty = true;
    }
    if (arcsDirty && state.sel) {
      drawArcs(vw, p);
      arcsDirty = false;
    }
    drawWisps(vw, p, now);

    const ck = `${Math.round((vw.z / ZMAX) * 100)}|${vw.z < 0.05}|${Math.abs(vw.z - 1) < 0.05}`;
    if (ck !== controlsKey) {
      controlsKey = ck;
      $('#zoom-level').style.width = `${Math.round((vw.z / ZMAX) * 100)}%`;
      $('#to-globe').setAttribute('aria-pressed', vw.z < 0.05);
      $('#to-flat').setAttribute('aria-pressed', Math.abs(vw.z - 1) < 0.05);
    }
  }

  // ---------- Turning and zooming ----------

  const pointers = new Map();
  const spread = () => {
    const [a, b] = [...pointers.values()];
    return Math.hypot(a.x - b.x, a.y - b.y) || 1;
  };
  const startDrag = ({ x, y }) => (drag = { x, y, lon: v.lon, lat: v.lat });

  worldEl.addEventListener('pointerdown', (e) => {
    if (e.target.closest('.wisp') || (e.pointerType === 'mouse' && e.button !== 0)) return;
    worldEl.setPointerCapture(e.pointerId);
    pointers.set(e.pointerId, { x: e.clientX, y: e.clientY });
    anim = null;
    idleSince = performance.now();
    if (pointers.size === 1) startDrag(pointers.get(e.pointerId));
    else if (pointers.size === 2) {
      drag = null;
      pinch = { d: spread(), z: v.z };
    }
    worldEl.classList.add('dragging');
  });
  worldEl.addEventListener('pointermove', (e) => {
    if (!pointers.has(e.pointerId)) return;
    pointers.set(e.pointerId, { x: e.clientX, y: e.clientY });
    idleSince = performance.now();
    if (pinch && pointers.size >= 2) {
      v.z = clamp(pinch.z + Math.log2(spread() / pinch.d), 0, ZMAX);
      clampLat();
    } else if (drag) {
      const k = 1 / (RAD * view().s);
      v.lon = wrap(drag.lon - (e.clientX - drag.x) * k);
      v.lat = drag.lat + (e.clientY - drag.y) * k;
      clampLat();
    }
  });
  const endPointer = (e) => {
    if (!pointers.delete(e.pointerId)) return;
    idleSince = performance.now();
    if (pointers.size < 2) pinch = null;
    if (pointers.size === 1) startDrag([...pointers.values()][0]);
    if (pointers.size === 0) {
      drag = null;
      worldEl.classList.remove('dragging');
    }
  };
  worldEl.addEventListener('pointerup', endPointer);
  worldEl.addEventListener('pointercancel', endPointer);

  worldEl.addEventListener(
    'wheel',
    (e) => {
      e.preventDefault();
      anim = null;
      idleSince = performance.now();
      const dy = e.deltaMode === 1 ? e.deltaY * 33 : e.deltaY;
      v.z = clamp(v.z - dy * 0.0012, 0, ZMAX);
      clampLat();
    },
    { passive: false },
  );

  const zoomBy = (dz) => {
    idleSince = performance.now();
    flyTo({ z: clamp(v.z + dz, 0, ZMAX) }, 500);
  };
  worldEl.addEventListener('keydown', (e) => {
    const step = 12 / Math.pow(2, Math.max(0, v.z - 1));
    const moves = { ArrowLeft: [-step, 0], ArrowRight: [step, 0], ArrowUp: [0, step], ArrowDown: [0, -step] };
    if (moves[e.key]) {
      idleSince = performance.now();
      flyTo({ lon: v.lon + moves[e.key][0], lat: clamp(v.lat + moves[e.key][1], -80, 80) }, 300);
    } else if (e.key === '+' || e.key === '=') zoomBy(0.7);
    else if (e.key === '-' || e.key === '_') zoomBy(-0.7);
    else return;
    e.preventDefault();
  });

  $('#zoom-in').addEventListener('click', () => zoomBy(0.7));
  $('#zoom-out').addEventListener('click', () => zoomBy(-0.7));
  $('#to-globe').addEventListener('click', () => {
    idleSince = performance.now() - 3000;
    flyTo({ z: 0, lat: 22 }, 1400);
  });
  $('#to-flat').addEventListener('click', () => flyTo({ z: 1, lat: 0 }, 1200));
  if (innerWidth < 500) $('#search').placeholder = 'Search tales and lands';
  if (matchMedia('(pointer: coarse)').matches) {
    $('#hint').textContent = 'Pinch to zoom. Zoom out and the world becomes a globe; drag to turn it.';
  }

  // ---------- The chosen tale ----------

  const state = { sel: null, mode: 'type', kin: [], reading: false, allKin: false, allOthers: false, collapsed: false };
  const taleCache = new Map();
  const loadTale = (id) => {
    if (!taleCache.has(id)) taleCache.set(id, json(`data/tales/${id}.json`).catch((err) => (taleCache.delete(id), Promise.reject(err))));
    return taleCache.get(id);
  };

  function pick(id, { fly = true, reading = false } = {}) {
    const tale = taleById.get(Number(id));
    if (!tale) return false;
    const same = state.sel === tale;
    state.sel = tale;
    state.reading = reading;
    if (!same) state.allKin = state.allOthers = false;
    state.collapsed = false;
    select();
    if (fly) {
      idleSince = performance.now();
      const { lon, lat } = tale;
      if (v.z < 0.7) flyTo({ lon, lat: clamp(lat, -60, 60) }, 1100);
      else if (v.z > 1.4) flyTo({ lon, lat }, 800);
    }
    return true;
  }

  // Light up the chosen tale, its kin and their countries, then fill in the panel.
  function select() {
    const sel = state.sel;
    state.kin = kinOf(sel, state.mode);
    forced = new Set([sel, ...state.kin.map((k) => k.tales[0])]);
    for (const [tale, b] of wispNodes) {
      b.classList.toggle('on', tale === sel);
      b.classList.toggle('kin', tale !== sel && forced.has(tale));
    }
    const kinCountries = new Set(state.kin.map((k) => k.place.country));
    for (const [name, node] of countryEls) {
      node.classList.toggle('o', name === sel.place.country);
      node.classList.toggle('k', name !== sel.place.country && kinCountries.has(name));
    }
    arcsDirty = true;
    renderPanel();
    const hash = state.reading ? `#read/${sel.id}` : `#${sel.place.id}/${sel.id}`;
    if (location.hash !== hash) history.replaceState(null, '', hash);
  }

  function renderPanel() {
    const sel = state.sel;
    panel.hidden = false;
    panel.classList.toggle('reading-mode', state.reading);
    panel.classList.toggle('collapsed', state.collapsed);
    const toggle = $('#sheet-toggle');
    toggle.setAttribute('aria-expanded', !state.collapsed);
    toggle.setAttribute('aria-label', state.collapsed ? 'Show more of this tale' : 'Show less of this tale');

    $('#tale-place').textContent = sel.place.name;
    $('#tale-title').textContent = sel.title;
    $('#tale-atu').textContent = `ATU ${sel.atu}${sel.typeName ? ` · ${sel.typeName}` : ''}`;
    $('#tale-family').textContent = [sel.kind, sel.family].filter(Boolean).join(' › ');
    $('#tale-summary').hidden = state.reading;
    $('#tale-reading').hidden = !state.reading;

    if (state.reading) renderReading(sel);
    else {
      $('#tale-excerpt').textContent = sel.excerpt;
      renderKin(sel);
      renderOthers(sel);
    }
  }

  function renderKin(sel) {
    const n = state.kin.length;
    $('#kin-head').textContent = !n
      ? 'No other tellings here yet'
      : state.mode === 'type'
        ? `Also told in ${n} ${n === 1 ? 'place' : 'places'}`
        : `Kindred tales in ${n} ${n === 1 ? 'place' : 'places'}`;
    $('#mode-type').setAttribute('aria-pressed', state.mode === 'type');
    $('#mode-family').setAttribute('aria-pressed', state.mode === 'family');
    const chips = $('#kin-chips');
    chips.replaceChildren();
    const shown = state.allKin ? state.kin : state.kin.slice(0, KIN_SHOWN);
    for (const { place, tales: list } of shown) {
      const b = el('button', 'kc', place.name);
      b.title = list.length === 1 ? `Open “${list[0].title}”` : `${list.length} tales; open “${list[0].title}”`;
      b.addEventListener('click', () => pick(list[0].id));
      chips.append(b);
    }
    if (shown.length < n) {
      const more = el('button', 'kc more-kin', `+ ${n - shown.length} more`);
      more.addEventListener('click', () => {
        state.allKin = true;
        renderKin(sel);
      });
      chips.append(more);
    }
  }

  function renderOthers(sel) {
    const others = sel.place.tales.filter((t) => t !== sel);
    $('#others').hidden = !others.length;
    $('#others-head').textContent = `More tales from ${sel.place.name}`;
    const list = $('#others-list');
    list.replaceChildren();
    for (const t of state.allOthers ? others : others.slice(0, OTHERS_SHOWN)) {
      const b = el('button', 'more', t.title);
      b.append(el('span', '', `ATU ${t.atu}`));
      b.addEventListener('click', () => pick(t.id));
      list.append(b);
    }
    if (!state.allOthers && others.length > OTHERS_SHOWN) {
      const all = el('button', 'more all', `All ${others.length + 1} tales from ${sel.place.name}`);
      all.addEventListener('click', () => {
        state.allOthers = true;
        renderOthers(sel);
      });
      list.append(all);
    }
  }

  async function renderReading(sel) {
    const reading = $('#reading');
    reading.replaceChildren(el('p', '', sel.excerpt));
    reading.scrollTop = 0;
    let tale;
    try {
      tale = await loadTale(sel.id);
    } catch {
      reading.append(el('p', 'source', 'The full tale could not be loaded. Try again later.'));
      return;
    }
    if (state.sel !== sel || !state.reading) return;
    reading.replaceChildren(...tale.paragraphs.map((p) => el('p', '', p)));
    const source = el('p', 'source', `Source: ${tale.source ?? 'unknown'} · via D. L. Ashliman’s Folktexts, in the trilogy Annotated Folktales.`);
    reading.append(source);
  }

  $('#read').addEventListener('click', () => {
    state.reading = true;
    select();
    $('#reading').focus({ preventScroll: true });
  });
  $('#back').addEventListener('click', () => {
    state.reading = false;
    select();
    $('#read').focus({ preventScroll: true });
  });
  for (const mode of ['type', 'family']) {
    $(`#mode-${mode}`).addEventListener('click', () => {
      state.mode = mode;
      state.allKin = false;
      select();
    });
  }
  $('#sheet-toggle').addEventListener('click', () => {
    state.collapsed = !state.collapsed;
    renderPanel();
  });

  // ---------- Search ----------

  const search = $('#search');
  const results = $('#results');
  let found = [];
  let active = -1;

  function runSearch() {
    const matches = searchTales(tales, search.value);
    if (!matches) return closeResults();
    found = matches;
    active = found.length ? 0 : -1;
    results.replaceChildren();
    if (!found.length) results.append(el('li', 'r-none', 'No tale matches that yet.'));
    found.forEach((t, i) => {
      const li = el('li');
      li.id = `result-${t.id}`;
      li.setAttribute('role', 'option');
      li.append(el('span', 'r-title', t.title), el('span', 'r-meta', `${t.place.name} · ATU ${t.atu}${t.typeName ? ` · ${t.typeName}` : ''}`));
      li.addEventListener('mousedown', (e) => e.preventDefault());
      li.addEventListener('click', () => choose(i));
      results.append(li);
    });
    results.hidden = false;
    search.setAttribute('aria-expanded', 'true');
    highlight();
  }
  function highlight() {
    [...results.children].forEach((li, i) => li.setAttribute('aria-selected', i === active));
    const li = found[active] && $(`#result-${found[active].id}`);
    if (li) {
      search.setAttribute('aria-activedescendant', li.id);
      li.scrollIntoView({ block: 'nearest' });
    } else search.removeAttribute('aria-activedescendant');
  }
  function closeResults() {
    results.hidden = true;
    found = [];
    active = -1;
    search.setAttribute('aria-expanded', 'false');
    search.removeAttribute('aria-activedescendant');
  }
  function choose(i) {
    const t = found[i];
    if (!t) return;
    search.value = '';
    closeResults();
    pick(t.id);
  }
  search.addEventListener('input', runSearch);
  search.addEventListener('focus', runSearch);
  search.addEventListener('blur', closeResults);
  search.addEventListener('keydown', (e) => {
    if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {
      if (!found.length) return;
      active = (active + (e.key === 'ArrowDown' ? 1 : -1) + found.length) % found.length;
      highlight();
    } else if (e.key === 'Enter') choose(Math.max(0, active));
    else if (e.key === 'Escape') {
      search.value = '';
      closeResults();
    } else return;
    e.preventDefault();
  });

  // ---------- Links: #germany, #germany/238, #read/238 ----------

  function fromHash() {
    const [a, b] = decodeURIComponent(location.hash.slice(1)).split('/');
    if (a === 'read' && b) return pick(b, { reading: true });
    if (b) return pick(b);
    const place = placeById.get(a);
    return place ? pick(place.tales[0].id) : false;
  }
  window.addEventListener('hashchange', fromHash);

  // ---------- Start ----------

  loading.hidden = true;
  measure();
  if (!fromHash()) {
    // Open on Cinderella, as told on the side of the globe that faces us.
    const facing = (t) => angle([t.lon, t.lat], [v.lon, v.lat]) < 50 * RAD;
    const first = tales.filter((t) => t.atu === '510A' && facing(t)).sort((a, b) => b.spacing - a.spacing)[0] ?? tales[0];
    pick(first.id, { fly: false });
  }
  measure();
  lay = { ...target };
  new ResizeObserver(measure).observe(panel);
  window.addEventListener('resize', measure);
  requestAnimationFrame(loop);

  // ---------- Background stars ----------

  function drawSky() {
    const sky = $('#sky');
    const W = innerWidth;
    const H = innerHeight;
    const rnd = random(42);
    const sizes = [0.5, 0.6, 0.8, 1, 1.2];
    const alphas = [0.2, 0.3, 0.45, 0.6];
    let dots = '';
    for (let i = Math.round((W * H) / 4800); i > 0; i--) {
      const x = (rnd() * W).toFixed(0);
      const y = (rnd() * H).toFixed(0);
      dots += `<circle cx="${x}" cy="${y}" r="${sizes[Math.floor(rnd() * 5)]}" opacity="${alphas[Math.floor(rnd() * 4)]}"></circle>`;
    }
    sky.setAttribute('viewBox', `0 0 ${W} ${H}`);
    sky.innerHTML = `<g fill="#DDE2FF">${dots}</g>`;
  }
})();
