// Folk Atlas: folktales as wisps of light over a globe that unrolls into a flat map.
// data/map.json and data/tales/<id>.json are generated by scripts/build-data.js from the
// trilogy Annotated Folktales; data/world.json holds Natural Earth countries (scripts/build-world.js).

import { geoDistance, geoEquirectangularRaw, geoGraticule10, geoOrthographicRaw, geoPath, geoProjectionMutator } from 'd3-geo';
import { feature, mesh } from 'topojson-client';
import { drawBackdrop, drawConstellation, drawMap, drawWisps, layer, wispSprites } from './render.js';
import { indexTale, searchTales } from './lib/search.js';
import { random, rankBySpread, smoothstep, sunflower } from './lib/wisps.js';

(async function () {
  const $ = (sel) => document.querySelector(sel);
  const RAD = Math.PI / 180;
  const ZMAX = 4.5;
  // Wisps show when they are at least this many pixels from every brighter wisp.
  const WISP_SPACING = 26;
  const KIN_SHOWN = 10;
  const FAM_SHOWN = 8;
  const OTHERS_SHOWN = 4;
  const FONT_SIZES = [18, 20, 22, 25, 28];
  const reduceMotion = matchMedia('(prefers-reduced-motion: reduce)').matches;

  const clamp = (x, a, b) => Math.max(a, Math.min(b, x));
  const ease = (t) => (t < 0.5 ? 2 * t * t : 1 - Math.pow(-2 * t + 2, 2) / 2);
  const wrap = (d) => ((((d + 180) % 360) + 360) % 360) - 180;
  const el = (tag, cls, text) => {
    const e = document.createElement(tag);
    if (cls) e.className = cls;
    if (text != null) e.textContent = text;
    return e;
  };

  const worldEl = $('#world');
  const panel = $('#panel');
  const loading = $('#loading');

  drawSky();
  window.addEventListener('resize', drawSky);

  const json = (url) =>
    fetch(url).then((r) => {
      if (!r.ok) throw new Error(`${url}: ${r.status}`);
      return r.json();
    });
  let data, world;
  try {
    [data, world] = await Promise.all([json('data/map.json'), json('data/world.json')]);
  } catch (err) {
    console.error(err);
    loading.textContent = 'The wisps could not be gathered. Try reloading.';
    return;
  }

  // ---------- Tales, places and their kin ----------

  const typeInfo = (atu) => {
    const [name = '', famIdx = -1] = data.types[atu] ?? [];
    const [family = '', kind = -1] = data.families[famIdx] ?? [];
    return { typeName: name, famIdx, family, kind: data.kinds[kind] ?? '' };
  };

  const places = data.places.map((p) => ({ ...p, tales: [] }));
  const placeById = new Map(places.map((p) => [p.id, p]));
  const tales = [];
  for (const [i, p] of data.places.entries()) {
    for (const [id, title, atu, excerpt] of p.tales) {
      const tale = { id, title, atu, excerpt, place: places[i], ...typeInfo(atu) };
      indexTale(tale, tale.typeName, `atu ${atu}`, p.name, tale.family, tale.kind, excerpt);
      places[i].tales.push(tale);
      tales.push(tale);
    }
  }
  const taleById = new Map(tales.map((t) => [t.id, t]));

  // key -> place -> tales of that key there
  const group = (keyOf) => {
    const map = new Map();
    for (const t of tales) {
      const key = keyOf(t);
      if (!map.has(key)) map.set(key, new Map());
      const byPlace = map.get(key);
      if (!byPlace.has(t.place)) byPlace.set(t.place, []);
      byPlace.get(t.place).push(t);
    }
    return map;
  };
  const byType = group((t) => t.atu);
  const byFamily = group((t) => t.famIdx);
  // The other places that tell the same tale (by type) or a tale of the same family, most tellings first.
  // Places in skip (those that tell the same tale) are left out of the same family.
  const kinOf = (tale, by, skip = []) => {
    const byPlace = (by === 'type' ? byType.get(tale.atu) : byFamily.get(tale.famIdx)) ?? new Map();
    const skipped = new Set(skip.map((k) => k.place));
    return [...byPlace]
      .filter(([place]) => place !== tale.place && !skipped.has(place))
      .sort((a, b) => b[1].length - a[1].length || a[0].name.localeCompare(b[0].name))
      .map(([place, list]) => ({ place, tales: list }));
  };

  // ---------- The map ----------

  const countries = feature(world, world.objects.countries).features;
  const land = feature(world, world.objects.land);
  // Borders and coasts as meshes: every shared border is projected and drawn once, not once per country.
  const borders = mesh(world, world.objects.countries, (a, b) => a !== b);
  const coast = mesh(world, world.objects.land);
  const graticule = geoGraticule10();
  const countryByName = new Map(countries.map((f) => [f.properties.name, f]));
  const backLayer = layer($('#backdrop'));
  const mapLayer = layer($('#map'));
  const wispLayer = layer($('#sky-wisps'), 1);
  let sprites = null;

  // Blends an orthographic globe (a = 0) into an equirectangular map (a = 1).
  const projectionAt = geoProjectionMutator((a) => (x, y) => {
    const p0 = geoOrthographicRaw(x, y);
    const p1 = geoEquirectangularRaw(x, y);
    return [p0[0] + a * (p1[0] - p0[0]), p0[1] + a * (p1[1] - p0[1])];
  });

  // z: 0 is the globe, 1 the flat world map, above 1 zoomed into the map.
  const v = { z: 0, lon: 20, lat: 22 };
  let anim = null;
  let drag = null;
  let pinch = null;
  let idleSince = 0;
  const t0 = performance.now();

  // Where the globe sits: centred on the screen below the header and controls. A tale panel at the side
  // overlays the globe's right edge a little; a bottom sheet (on phones) pushes the globe up instead.
  let target = null;
  let lay = null;
  const sheetQuery = matchMedia('(max-width: 760px)');
  function measure() {
    const W = innerWidth;
    const H = innerHeight;
    let y0 = Math.max(56, $('.top').getBoundingClientRect().bottom - 8);
    let y1 = H;
    const controls = $('.controls').getBoundingClientRect();
    if (controls.top < H * 0.3) y0 = Math.max(y0, controls.bottom + 16);
    if (sheetQuery.matches && !panel.hidden) y1 = panel.getBoundingClientRect().top;
    let k = Math.min(W / 1056, (y1 - y0) / 828);
    if (!sheetQuery.matches) {
      // Keep the globe from reaching more than 40% of the way under the side panel, open or not.
      const css = getComputedStyle(document.documentElement);
      const panelW = parseFloat(css.getPropertyValue('--panel-w'));
      const panelLeft = W - parseFloat(css.getPropertyValue('--gutter')) - panelW;
      k = Math.min(k, (panelLeft + 0.4 * panelW - W / 2) / 280);
    }
    k = clamp(k, 0.25, 1.8);
    const cx = W / 2;
    target = { W, H, cx, cy: (y0 + y1) / 2, sg: 280 * k, sf: 160 * k, shift: (W / 2 - cx) * 0.58 };
    if (!lay) lay = { ...target };
    backLayer.resize(W, H);
    mapLayer.resize(W, H);
    if (wispLayer.resize(W, H) || !sprites) sprites = wispSprites(wispLayer.dpr);
    mapDirty = true;
  }
  function stepLayout() {
    let changed = false;
    for (const key of ['cx', 'cy', 'sg', 'sf', 'shift']) {
      const d = target[key] - lay[key];
      if (d === 0) continue;
      lay[key] = Math.abs(d) < 0.3 ? target[key] : lay[key] + d * 0.18;
      changed = true;
    }
    lay.W = target.W;
    lay.H = target.H;
    return changed;
  }

  function view() {
    const z = clamp(v.z, 0, ZMAX);
    const a = ease(clamp(z, 0, 1));
    const fade = ease(clamp((z - 1) / 0.7, 0, 1));
    const s = z <= 1 ? lay.sg + (lay.sf - lay.sg) * a : lay.sf * Math.pow(2, z - 1);
    // Zoomed in, keep the map's edges beyond the edges of the screen.
    const maxN = 90 - lay.cy / s / RAD;
    const maxS = 90 - (lay.H - lay.cy) / s / RAD;
    const latF = -maxS <= maxN ? clamp(v.lat, -maxS, maxN) : (maxN - maxS) / 2;
    return {
      z,
      a,
      s,
      fade,
      cx: lay.cx + lay.shift * fade,
      cy: lay.cy,
      lon: v.lon,
      latF,
      rotLat: clamp(v.lat, -70, 70) * (1 - a),
      clip: a < 0.999 ? 90 + 89.5 * a : null,
    };
  }

  function project(vw) {
    const p = projectionAt(vw.a);
    p.rotate([-vw.lon, -vw.rotLat])
      .scale(vw.s)
      .translate([vw.cx, vw.cy + vw.latF * RAD * vw.s * vw.a])
      .clipAngle(vw.clip)
      .precision(0.6);
    return p;
  }

  // The astrolabe ring around the globe (drawn in render.js); it grows away as the map unrolls.
  function frame(vw) {
    const m = 1 + 3 * vw.fade;
    return {
      cx: vw.cx,
      cy: vw.cy,
      rx: vw.s * (1.18 + (2.95 - 1.18) * vw.a) * m,
      ry: vw.s * (1.18 + (1.72 - 1.18) * vw.a) * m,
      op: 1 - vw.fade,
    };
  }

  // How visible a point is: fades out near the globe's edge.
  const visibility = (vw, lonLat) =>
    vw.clip === null ? 1 : clamp((vw.clip - geoDistance(lonLat, [vw.lon, vw.rotLat]) / RAD) / 5, 0, 1);

  // Constellation: arcs from the chosen tale to a kindred tale in every place that has one, gold to
  // the same tale and silver to the same family, kept as Path2Ds until the view or the choice changes.
  function constellation(vw, p) {
    const from = [state.sel.lon, state.sel.lat];
    const arcsTo = (kin) => {
      const path2d = new Path2D();
      const path = geoPath(p, path2d);
      const ends = [];
      for (const k of kin) {
        const to = [k.tales[0].lon, k.tales[0].lat];
        path({ type: 'LineString', coordinates: [from, to] });
        const alpha = visibility(vw, to);
        const xy = alpha > 0 ? p(to) : null;
        if (xy) ends.push({ x: xy[0], y: xy[1], alpha });
      }
      return { path: path2d, ends };
    };
    return { gold: arcsTo(state.kin), silver: arcsTo(state.fam) };
  }

  // ---------- Wisps: every tale is one, shown as zoom makes room ----------

  // Each tale's spot: its place's most widely told tale at the place itself, the others around it.
  for (const place of places) {
    place.tales.sort((a, b) => byType.get(b.atu).size - byType.get(a.atu).size || a.id - b.id);
    sunflower(place.tales.length, place.lat).forEach(([dLon, dLat], i) => {
      place.tales[i].lon = place.lng + dLon;
      place.tales[i].lat = place.lat + dLat;
    });
  }
  const { spacing } = rankBySpread(
    tales.map((t) => [t.lon, t.lat]),
    7,
  );
  for (const [i, tale] of tales.entries()) {
    const rnd = random(tale.id * 7919);
    tale.spacing = spacing[i];
    // Drift a few pixels around its spot, and come and go slowly where the zoom is about to show or hide it.
    tale.drift = { r: 2.5 + rnd() * 3, f: [0, 0, 0, 0].map(() => 0.12 + rnd() * 0.25), ph: [0, 0, 0, 0].map(() => rnd() * Math.PI * 2) };
    tale.tide = { f: (2 * Math.PI) / (25 + rnd() * 35), ph: rnd() * Math.PI * 2 };
  }

  // The chosen tale and its kin always show: tale -> 'on' | 'kin' (same tale) | 'sib' (same family)
  let forced = new Map();
  const wispState = (tale) => forced.get(tale) ?? '';
  for (const tale of tales) {
    tale.dur = 4 + ((tale.id * 1.37) % 3.5);
    tale.delay = (tale.id * 1.91) % 7;
  }

  // The wisps on screen this frame: where they are and how bright, for drawing and for pointing at.
  function placeWisps(vw, p, fr, t) {
    const shown = [];
    const minSpacing = WISP_SPACING / vw.s; // radians on the ground
    for (const tale of tales) {
      let alpha = 1;
      if (!forced.has(tale)) {
        const tide = 1 + 0.3 * Math.sin(tale.tide.f * t + tale.tide.ph);
        alpha = smoothstep((tale.spacing / (minSpacing * tide) - 1) / 0.6);
        if (alpha <= 0.01) continue;
      }
      const { r, f, ph } = tale.drift;
      const k = r / (vw.s * RAD); // pixels -> degrees
      const cl = Math.max(0.3, Math.cos(tale.lat * RAD));
      const lon = tale.lon + (k * (0.65 * Math.sin(f[0] * t + ph[0]) + 0.35 * Math.sin(f[1] * 1.7 * t + ph[1]))) / cl;
      const lat = tale.lat + k * (0.65 * Math.sin(f[2] * t + ph[2]) + 0.35 * Math.sin(f[3] * 1.7 * t + ph[3]));
      let vis = visibility(vw, [lon, lat]);
      if (vis <= 0) continue;
      const xy = p([lon, lat]);
      if (!xy || xy[0] < -30 || xy[0] > lay.W + 30 || xy[1] < -30 || xy[1] > lay.H + 30) continue;
      const ex = (xy[0] - fr.cx) / fr.rx;
      const ey = (xy[1] - fr.cy) / fr.ry;
      vis = Math.min(vis, clamp((1 - ex * ex - ey * ey) / 0.06, 0, 1));
      if (vis * alpha <= 0.01) continue;
      shown.push({ tale, x: xy[0], y: xy[1], alpha: vis * alpha, state: wispState(tale), dur: tale.dur, delay: tale.delay });
    }
    return shown;
  }

  // The wisp nearest a point on screen, if one is close enough to point at.
  let onScreen = [];
  function wispAt(x, y, reach = 20) {
    let best = null;
    let bestD = reach * reach;
    for (const w of onScreen) {
      const d = (w.x - x) ** 2 + (w.y - y) ** 2;
      if (d < bestD) (best = w), (bestD = d);
    }
    return best;
  }

  // For keyboards and screen readers: a button for every wisp on screen, in a visually hidden list.
  const wispList = $('#wisps');
  const wispButtons = new Map();
  let listKey = '';
  let listAt = 0;
  let focused = null;
  function updateWispList(now) {
    if (now - listAt < 300) return;
    listAt = now;
    for (const w of onScreen) {
      const b = wispButtons.get(w.tale);
      if (b) (b.dataset.x = w.x.toFixed(0)), (b.dataset.y = w.y.toFixed(0));
    }
    const key = onScreen.map((w) => w.tale.id).join();
    if (key === listKey) return;
    listKey = key;
    const keep = new Set(onScreen.map((w) => w.tale));
    for (const [tale, b] of wispButtons) {
      if (keep.has(tale) || b === document.activeElement) continue;
      b.remove();
      wispButtons.delete(tale);
    }
    for (const { tale } of onScreen) {
      if (wispButtons.has(tale)) continue;
      const b = el('button', 'wisp');
      b.type = 'button';
      b.setAttribute('aria-label', `${tale.title}, ${tale.place.name}`);
      b.addEventListener('click', () => pick(tale.id));
      b.addEventListener('focus', () => (focused = tale));
      b.addEventListener('blur', () => focused === tale && (focused = null));
      wispList.append(b);
      wispButtons.set(tale, b);
    }
    for (const w of onScreen) Object.assign(wispButtons.get(w.tale).dataset, { x: w.x.toFixed(0), y: w.y.toFixed(0) });
    markWisps();
  }
  function markWisps() {
    for (const [tale, b] of wispButtons) {
      for (const cls of ['on', 'kin', 'sib']) b.classList.toggle(cls, forced.get(tale) === cls);
    }
  }

  // Names under the chosen, the pointed-at and the focused wisp: a few elements, so the text stays sharp.
  const labelsEl = $('#labels');
  const labels = new Map(); // tale -> element
  function drawLabels() {
    const named = onScreen.filter((w) => w.tale === state.sel || w.tale === hovered || w.tale === focused);
    for (const [tale, node] of labels) {
      if (named.some((w) => w.tale === tale)) continue;
      node.remove();
      labels.delete(tale);
    }
    for (const w of named) {
      let node = labels.get(w.tale);
      if (!node) labelsEl.append((node = el('span', 'wl', w.tale.title))), labels.set(w.tale, node);
      node.style.transform = `translate(${w.x.toFixed(1)}px,${(w.y + 14).toFixed(1)}px) translateX(-50%)`;
      node.style.opacity = Math.min(1, w.alpha * 1.5).toFixed(2);
    }
  }

  // Country highlights fade in and out over half a second.
  const LEVELS = [['sib', 'toSib'], ['kin', 'toKin'], ['own', 'toOwn']];
  const highlights = new Map(); // feature -> { sib, kin, own, toSib, toKin, toOwn }
  function setHighlights(own, kin, sib) {
    for (const h of highlights.values()) h.toSib = h.toKin = h.toOwn = 0;
    // A country lights up once, in the brightest way it is kin.
    const lit = new Set();
    const mark = (name, key) => {
      const f = countryByName.get(name);
      if (!f || lit.has(f)) return;
      lit.add(f);
      if (!highlights.has(f)) highlights.set(f, { sib: 0, kin: 0, own: 0, toSib: 0, toKin: 0, toOwn: 0 });
      highlights.get(f)[key] = 1;
    };
    mark(own, 'toOwn');
    for (const name of kin) mark(name, 'toKin');
    for (const name of sib) mark(name, 'toSib');
    mapDirty = true;
  }
  function stepHighlights(dt) {
    let moving = false;
    const k = Math.min(1, dt / 500);
    for (const [f, h] of highlights) {
      for (const [key, to] of LEVELS) {
        const d = h[to] - h[key];
        if (d === 0) continue;
        h[key] = Math.abs(d) <= k ? h[to] : h[key] + Math.sign(d) * k;
        moving = true;
      }
      if (LEVELS.every(([key, to]) => !h[key] && !h[to])) highlights.delete(f);
    }
    return moving;
  }

  // ---------- Animation loop ----------

  function flyTo(to, dur = 900) {
    const t = { z: to.z ?? v.z, lon: to.lon ?? v.lon, lat: to.lat ?? v.lat };
    anim = { start: performance.now(), dur, from: { ...v }, to: t, dlon: wrap(t.lon - v.lon) };
  }

  function stepView(now, dt) {
    if (anim) {
      const k = clamp((now - anim.start) / anim.dur, 0, 1);
      const e = ease(k);
      v.z = anim.from.z + (anim.to.z - anim.from.z) * e;
      v.lon = wrap(anim.from.lon + anim.dlon * e);
      v.lat = anim.from.lat + (anim.to.lat - anim.from.lat) * e;
      if (k >= 1) anim = null;
    } else if (!state.sel && !drag && !pinch && !reduceMotion && v.z < 0.4 && now - idleSince > 4000) {
      v.lon = wrap(v.lon + (3.5 * dt) / 1000);
    }
  }

  function clampLat() {
    if (v.z >= 1) v.lat = view().latF;
    else v.lat = clamp(v.lat, -70, 70);
  }

  let mapKey = '';
  let backdropKey = '';
  let mapDirty = true;
  let arcs = null;
  let arcsKey = '';
  let hovered = null;
  let controlsKey = '';
  let prev = performance.now();
  // While you turn, zoom or fly, draw at up to 60 frames a second (not 120 on a ProMotion screen);
  // while the map only turns and breathes on its own, 30 are enough and leave the machine idle.
  let activeUntil = 0;
  const keepBusy = (ms = 600) => (activeUntil = Math.max(activeUntil, performance.now() + ms));
  const frameTimes = new URLSearchParams(location.search).has('perf') ? (window.frameTimes = []) : null;
  function loop(now) {
    requestAnimationFrame(loop);
    // The reading view covers the map: leave it be until the view closes.
    if (state.reading) return;
    const busy = anim || drag || pinch || now < activeUntil;
    if (now - prev < 1000 / (busy ? 60 : 30) - 4) return;
    const started = performance.now();
    const dt = Math.min(100, now - prev);
    prev = now;
    if (stepLayout()) keepBusy();
    stepView(now, dt);
    if (stepHighlights(dt)) mapDirty = true;
    const vw = view();
    const p = project(vw);
    const fr = frame(vw);
    const key = [vw.z, v.lon, v.lat, lay.cx, lay.cy, lay.sg, lay.sf].map((n) => n.toFixed(3)).join();
    // The backdrop doesn't change as the globe turns: only the zoom, the layout (and, on the map, the latitude) move it.
    const backKey = [vw.z, vw.a > 0 ? vw.latF : 0, lay.cx, lay.cy, lay.sg, lay.sf].map((n) => n.toFixed(3)).join();
    if (backKey !== backdropKey || mapDirty) {
      backdropKey = backKey;
      drawBackdrop(backLayer, { vw, projection: p, frame: fr });
    }
    if (key !== mapKey || mapDirty) {
      mapKey = key;
      mapDirty = false;
      drawMap(mapLayer, { vw, projection: p, frame: fr, land, borders, coast, graticule, highlights });
    }
    if (!state.sel) arcs = null;
    else if (arcsKey !== `${key}|${state.sel.id}`) {
      arcsKey = `${key}|${state.sel.id}`;
      arcs = constellation(vw, p);
    }

    const t = reduceMotion ? 0 : (now - t0) / 1000;
    onScreen = placeWisps(vw, p, fr, t);
    wispLayer.clear();
    const ctx = wispLayer.ctx;
    ctx.save();
    ctx.beginPath();
    ctx.ellipse(fr.cx, fr.cy, fr.rx, fr.ry, 0, 0, Math.PI * 2);
    ctx.clip();
    drawConstellation(ctx, sprites, arcs, t);
    ctx.restore();
    drawWisps(ctx, sprites, onScreen, t);
    drawLabels();
    updateWispList(now);
    frameTimes?.push(performance.now() - started);

    const ck = `${Math.round((vw.z / ZMAX) * 100)}|${vw.z < 0.05}|${Math.abs(vw.z - 1) < 0.05}`;
    if (ck !== controlsKey) {
      controlsKey = ck;
      $('#zoom-level').style.width = `${Math.round((vw.z / ZMAX) * 100)}%`;
      $('#to-globe').setAttribute('aria-pressed', vw.z < 0.05);
      $('#to-flat').setAttribute('aria-pressed', Math.abs(vw.z - 1) < 0.05);
    }
  }

  // ---------- Turning and zooming ----------

  const pointers = new Map();
  const spread = () => {
    const [a, b] = [...pointers.values()];
    return Math.hypot(a.x - b.x, a.y - b.y) || 1;
  };
  const startDrag = ({ x, y }) => (drag = { x, y, lon: v.lon, lat: v.lat });

  // A tap or click that hardly moved opens the wisp under it.
  let press = null;
  worldEl.addEventListener('pointerdown', (e) => {
    if (e.pointerType === 'mouse' && e.button !== 0) return;
    worldEl.setPointerCapture(e.pointerId);
    press = pointers.size === 0 ? { x: e.clientX, y: e.clientY, type: e.pointerType } : null;
    pointers.set(e.pointerId, { x: e.clientX, y: e.clientY });
    anim = null;
    idleSince = performance.now();
    if (pointers.size === 1) startDrag(pointers.get(e.pointerId));
    else if (pointers.size === 2) {
      drag = null;
      pinch = { d: spread(), z: v.z };
    }
    worldEl.classList.add('dragging');
  });
  worldEl.addEventListener('pointermove', (e) => {
    if (!pointers.has(e.pointerId)) {
      if (e.pointerType === 'mouse') {
        const h = wispAt(e.clientX, e.clientY)?.tale ?? null;
        if (h !== hovered) keepBusy(300);
        hovered = h;
        worldEl.classList.toggle('pointing', !!hovered);
      }
      return;
    }
    if (press && Math.hypot(e.clientX - press.x, e.clientY - press.y) > 6) press = null;
    pointers.set(e.pointerId, { x: e.clientX, y: e.clientY });
    idleSince = performance.now();
    keepBusy();
    if (pinch && pointers.size >= 2) {
      v.z = clamp(pinch.z + Math.log2(spread() / pinch.d), 0, ZMAX);
      clampLat();
    } else if (drag) {
      const k = 1 / (RAD * view().s);
      v.lon = wrap(drag.lon - (e.clientX - drag.x) * k);
      v.lat = drag.lat + (e.clientY - drag.y) * k;
      clampLat();
    }
  });
  const endPointer = (e) => {
    if (!pointers.delete(e.pointerId)) return;
    if (press && e.type === 'pointerup' && pointers.size === 0) {
      const w = wispAt(press.x, press.y, press.type === 'mouse' ? 20 : 28);
      if (w) pick(w.tale.id);
    }
    press = null;
    idleSince = performance.now();
    if (pointers.size < 2) pinch = null;
    if (pointers.size === 1) startDrag([...pointers.values()][0]);
    if (pointers.size === 0) {
      drag = null;
      worldEl.classList.remove('dragging');
    }
  };
  worldEl.addEventListener('pointerup', endPointer);
  worldEl.addEventListener('pointercancel', endPointer);
  worldEl.addEventListener('pointerleave', () => {
    hovered = null;
    worldEl.classList.remove('pointing');
  });

  worldEl.addEventListener(
    'wheel',
    (e) => {
      e.preventDefault();
      anim = null;
      idleSince = performance.now();
      keepBusy();
      const dy = e.deltaMode === 1 ? e.deltaY * 33 : e.deltaY;
      v.z = clamp(v.z - dy * 0.0012, 0, ZMAX);
      clampLat();
    },
    { passive: false },
  );

  const zoomBy = (dz) => {
    idleSince = performance.now();
    flyTo({ z: clamp(v.z + dz, 0, ZMAX) }, 500);
  };
  worldEl.addEventListener('keydown', (e) => {
    const step = 12 / Math.pow(2, Math.max(0, v.z - 1));
    const moves = { ArrowLeft: [-step, 0], ArrowRight: [step, 0], ArrowUp: [0, step], ArrowDown: [0, -step] };
    if (moves[e.key]) {
      idleSince = performance.now();
      flyTo({ lon: v.lon + moves[e.key][0], lat: clamp(v.lat + moves[e.key][1], -80, 80) }, 300);
    } else if (e.key === '+' || e.key === '=') zoomBy(0.7);
    else if (e.key === '-' || e.key === '_') zoomBy(-0.7);
    else return;
    e.preventDefault();
  });

  $('#zoom-in').addEventListener('click', () => zoomBy(0.7));
  $('#zoom-out').addEventListener('click', () => zoomBy(-0.7));
  $('#to-globe').addEventListener('click', () => {
    idleSince = performance.now() - 3000;
    flyTo({ z: 0, lat: 22 }, 1400);
  });
  $('#to-flat').addEventListener('click', () => flyTo({ z: 1, lat: 0 }, 1200));
  if (innerWidth < 500) $('#search').placeholder = 'Search tales and lands';
  if (matchMedia('(pointer: coarse)').matches) {
    $('#hint').textContent = 'Pinch to zoom. Zoom out and the world becomes a globe; drag to turn it.';
  }

  // ---------- The chosen tale ----------

  const state = { sel: null, kin: [], fam: [], reading: false, allKin: false, allFam: false, allOthers: false, collapsed: false };
  const taleCache = new Map();
  const loadTale = (id) => {
    if (!taleCache.has(id)) taleCache.set(id, json(`data/tales/${id}.json`).catch((err) => (taleCache.delete(id), Promise.reject(err))));
    return taleCache.get(id);
  };

  function pick(id, { fly = true, reading = false } = {}) {
    const tale = taleById.get(Number(id));
    if (!tale) return false;
    const same = state.sel === tale;
    const wasReading = state.reading;
    state.sel = tale;
    state.reading = reading;
    if (!same) state.allKin = state.allFam = state.allOthers = false;
    state.collapsed = false;
    select();
    if (reading && (!same || !wasReading)) renderReader(tale);
    if (!reading && wasReading) closeReaderView();
    if (fly) {
      idleSince = performance.now();
      const { lon, lat } = tale;
      if (v.z < 0.7) flyTo({ lon, lat: clamp(lat, -60, 60) }, 1100);
      else if (v.z > 1.4) flyTo({ lon, lat }, 800);
    }
    return true;
  }

  // Let go of the chosen tale: the panel closes and the globe may turn on its own again.
  function deselect() {
    if (!state.sel) return;
    const wasIn = state.reading || panel.contains(document.activeElement);
    if (state.reading) closeReaderView();
    state.sel = null;
    state.reading = false;
    state.kin = [];
    state.fam = [];
    arcsKey = '';
    forced = new Map();
    markWisps();
    setHighlights(null, [], []);
    panel.hidden = true;
    idleSince = performance.now();
    if (location.hash) history.replaceState(null, '', location.pathname + location.search);
    if (wasIn) worldEl.focus({ preventScroll: true });
  }

  // Light up the chosen tale, its kin and their countries, then fill in the panel.
  function select() {
    const sel = state.sel;
    state.kin = kinOf(sel, 'type');
    state.fam = kinOf(sel, 'family', state.kin);
    forced = new Map([...state.fam.map((k) => [k.tales[0], 'sib']), ...state.kin.map((k) => [k.tales[0], 'kin']), [sel, 'on']]);
    markWisps();
    setHighlights(
      sel.place.country,
      state.kin.map((k) => k.place.country),
      state.fam.map((k) => k.place.country),
    );
    renderPanel();
    const hash = state.reading ? `#read/${sel.id}` : `#${sel.place.id}/${sel.id}`;
    if (location.hash !== hash) history.replaceState(null, '', hash);
  }

  const typeLabel = (t) => `ATU ${t.atu}${t.typeName ? ` · ${t.typeName}` : ''}`;
  const nPlaces = (n) => `${n} ${n === 1 ? 'place' : 'places'}`;

  function renderPanel() {
    const sel = state.sel;
    panel.hidden = false;
    panel.classList.toggle('collapsed', state.collapsed);
    const toggle = $('#sheet-toggle');
    toggle.setAttribute('aria-expanded', !state.collapsed);
    toggle.setAttribute('aria-label', state.collapsed ? 'Show more of this tale' : 'Show less of this tale');

    $('#tale-place').textContent = sel.place.name;
    $('#tale-title').textContent = sel.title;
    $('#tale-atu').textContent = typeLabel(sel);
    $('#tale-family').textContent = [sel.kind, sel.family].filter(Boolean).join(' › ');
    $('#tale-excerpt').textContent = sel.excerpt;
    const nKin = state.kin.length;
    const nFam = state.fam.length;
    $('#kin-head').textContent = nKin ? `Same tale · told in ${nPlaces(nKin)}` : 'Same tale · not recorded elsewhere yet';
    $('#fam-head').textContent = nFam ? `Same family · ${nPlaces(nFam)}` : 'Same family · no other places yet';
    renderChips($('#kin-chips'), state.kin, '', state.allKin ? Infinity : KIN_SHOWN, () => ((state.allKin = true), renderPanel()));
    renderChips($('#fam-chips'), state.fam, 'silver', state.allFam ? Infinity : FAM_SHOWN, () => ((state.allFam = true), renderPanel()));
    renderOthers(sel);
  }

  // A chip for every place in kin, up to max, and a "+ n more" chip that shows the rest.
  function renderChips(box, kin, cls, max, showAll, opts) {
    box.replaceChildren();
    for (const { place, tales: list } of kin.slice(0, max)) {
      const b = el('button', `kc ${cls}`.trim(), place.name);
      b.title = list.length === 1 ? `Open “${list[0].title}”` : `${list.length} tales; open “${list[0].title}”`;
      b.addEventListener('click', () => pick(list[0].id, opts));
      box.append(b);
    }
    if (kin.length > max) {
      const more = el('button', 'kc more-kin', `+ ${kin.length - max} more`);
      more.addEventListener('click', showAll);
      box.append(more);
    }
  }

  function otherRow(t, opts) {
    const b = el('button', 'more', t.title);
    b.append(el('span', '', `ATU ${t.atu}`));
    b.addEventListener('click', () => pick(t.id, opts));
    return b;
  }

  function renderOthers(sel) {
    const others = sel.place.tales.filter((t) => t !== sel);
    $('#others').hidden = !others.length;
    $('#others-head').textContent = `More tales from ${sel.place.name}`;
    const list = $('#others-list');
    list.replaceChildren(...(state.allOthers ? others : others.slice(0, OTHERS_SHOWN)).map((t) => otherRow(t)));
    if (!state.allOthers && others.length > OTHERS_SHOWN) {
      const all = el('button', 'more all', `All ${others.length + 1} tales from ${sel.place.name}`);
      all.addEventListener('click', () => {
        state.allOthers = true;
        renderOthers(sel);
      });
      list.append(all);
    }
  }

  $('#read').addEventListener('click', () => pick(state.sel.id, { fly: false, reading: true }));
  $('#close').addEventListener('click', deselect);
  document.addEventListener('keydown', (e) => {
    if (e.key !== 'Escape' || !state.sel || e.target === search) return;
    if (state.reading) closeReader();
    else deselect();
  });
  $('#sheet-toggle').addEventListener('click', () => {
    state.collapsed = !state.collapsed;
    renderPanel();
  });

  // ---------- The reading view ----------

  const reader = $('#reader');
  const readerScroll = $('#r-scroll');
  const readerBar = $('#r-bar');
  const readingEl = $('#reading');

  async function renderReader(sel) {
    document.body.classList.add('reading');
    reader.hidden = false;
    readerScroll.scrollTop = 0;
    readerBar.classList.remove('shown');
    $('#r-place').textContent = sel.place.name;
    $('#r-title').textContent = sel.title;
    $('#r-mini-title').textContent = sel.title;
    $('#r-mini-place').textContent = sel.place.name;
    $('#r-type').textContent = [typeLabel(sel), sel.family].filter(Boolean).join(' · ');
    $('#r-source').replaceChildren();
    $('#r-kin').hidden = !state.kin.length;
    renderChips($('#r-kin-chips'), state.kin, '', Infinity, null, { reading: true });
    const others = sel.place.tales.filter((t) => t !== sel);
    $('#r-others').hidden = !others.length;
    $('#r-others-head').textContent = `More tales from ${sel.place.name}`;
    $('#r-others-list').replaceChildren(...others.slice(0, OTHERS_SHOWN).map((t) => otherRow(t, { reading: true })));
    readingEl.replaceChildren(firstParagraph(sel.excerpt));
    readingEl.focus({ preventScroll: true });

    let tale;
    try {
      tale = await loadTale(sel.id);
    } catch {
      readingEl.append(el('p', 'r-source', 'The full tale could not be loaded. Try again later.'));
      return;
    }
    if (state.sel !== sel || !state.reading) return;
    const [first = '', ...rest] = tale.paragraphs;
    readingEl.replaceChildren(firstParagraph(first), ...rest.map((p) => el('p', '', p)));
    const link = (href, text) => Object.assign(el('a', '', text), { href, target: '_blank', rel: 'noopener' });
    $('#r-source').replaceChildren(
      ...(tale.source ? [`Source: ${tale.source}`, el('br')] : []),
      'From D. L. Ashliman’s ',
      link('https://sites.pitt.edu/~dash/folktexts.html', 'Folktexts'),
      ', via the Annotated Folktales in ',
      link('https://github.com/j-hagedorn/trilogy', 'trilogy'),
      ' (CC BY-SA 4.0).',
    );
  }

  // The first paragraph opens with its first letter as a framed initial (leading quotes dropped).
  function firstParagraph(text) {
    const p = el('p');
    const lead = text.match(/^["'‘“(]*/)[0].length;
    const letter = text.charAt(lead).toUpperCase();
    if (!letter) return p;
    const cap = el('span', 'cap');
    cap.setAttribute('aria-hidden', 'true');
    cap.append(el('i'), el('i'), el('i'), el('i'), el('b', '', letter));
    p.append(cap, el('span', 'sr-only', letter), text.slice(lead + 1));
    return p;
  }

  function closeReaderView() {
    document.body.classList.remove('reading');
    reader.hidden = true;
    mapDirty = true;
  }
  // Back to the atlas, with the tale still chosen.
  function closeReader() {
    if (!state.reading) return;
    pick(state.sel.id, { fly: false });
    $('#read').focus({ preventScroll: true });
  }
  $('#back').addEventListener('click', closeReader);
  $('#r-close').addEventListener('click', closeReader);
  readerScroll.addEventListener('scroll', () => readerBar.classList.toggle('shown', readerScroll.scrollTop > 280), { passive: true });

  // Text size, remembered on this device.
  let fontStep = 2;
  try {
    const saved = localStorage.getItem('folk-atlas:text-size');
    if (saved !== null && Number(saved) in FONT_SIZES) fontStep = Number(saved);
  } catch {}
  function setFontStep(step) {
    fontStep = clamp(step, 0, FONT_SIZES.length - 1);
    readingEl.style.setProperty('--fs', `${FONT_SIZES[fontStep]}px`);
    $('#fs-down').disabled = fontStep === 0;
    $('#fs-up').disabled = fontStep === FONT_SIZES.length - 1;
  }
  const stepFont = (d) => {
    setFontStep(fontStep + d);
    try {
      localStorage.setItem('folk-atlas:text-size', String(fontStep));
    } catch {}
  };
  setFontStep(fontStep);
  $('#fs-down').addEventListener('click', () => stepFont(-1));
  $('#fs-up').addEventListener('click', () => stepFont(1));

  // ---------- Search ----------

  const search = $('#search');
  const results = $('#results');
  let found = [];
  let active = -1;

  function runSearch() {
    const matches = searchTales(tales, search.value);
    if (!matches) return closeResults();
    found = matches;
    active = found.length ? 0 : -1;
    results.replaceChildren();
    if (!found.length) results.append(el('li', 'r-none', 'No tale matches that yet.'));
    found.forEach((t, i) => {
      const li = el('li');
      li.id = `result-${t.id}`;
      li.setAttribute('role', 'option');
      li.append(el('span', 'r-title', t.title), el('span', 'r-meta', `${t.place.name} · ATU ${t.atu}${t.typeName ? ` · ${t.typeName}` : ''}`));
      li.addEventListener('mousedown', (e) => e.preventDefault());
      li.addEventListener('click', () => choose(i));
      results.append(li);
    });
    results.hidden = false;
    search.setAttribute('aria-expanded', 'true');
    highlight();
  }
  function highlight() {
    [...results.children].forEach((li, i) => li.setAttribute('aria-selected', i === active));
    const li = found[active] && $(`#result-${found[active].id}`);
    if (li) {
      search.setAttribute('aria-activedescendant', li.id);
      li.scrollIntoView({ block: 'nearest' });
    } else search.removeAttribute('aria-activedescendant');
  }
  function closeResults() {
    results.hidden = true;
    found = [];
    active = -1;
    search.setAttribute('aria-expanded', 'false');
    search.removeAttribute('aria-activedescendant');
  }
  function choose(i) {
    const t = found[i];
    if (!t) return;
    search.value = '';
    closeResults();
    pick(t.id);
  }
  search.addEventListener('input', runSearch);
  search.addEventListener('focus', runSearch);
  search.addEventListener('blur', closeResults);
  search.addEventListener('keydown', (e) => {
    if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {
      if (!found.length) return;
      active = (active + (e.key === 'ArrowDown' ? 1 : -1) + found.length) % found.length;
      highlight();
    } else if (e.key === 'Enter') choose(Math.max(0, active));
    else if (e.key === 'Escape') {
      search.value = '';
      closeResults();
    } else return;
    e.preventDefault();
  });

  // ---------- Links: #germany, #germany/238, #read/238 ----------

  function fromHash() {
    const [a, b] = decodeURIComponent(location.hash.slice(1)).split('/');
    if (a === 'read' && b) return pick(b, { reading: true });
    if (b) return pick(b);
    const place = placeById.get(a);
    return place ? pick(place.tales[0].id) : false;
  }
  window.addEventListener('hashchange', () => fromHash() || deselect());

  // ---------- Start ----------

  loading.hidden = true;
  measure();
  fromHash();
  measure();
  lay = { ...target };
  new ResizeObserver(measure).observe(panel);
  window.addEventListener('resize', measure);
  requestAnimationFrame(loop);
  document.fonts?.ready.then(() => (mapDirty = true));

  // ---------- Background stars ----------

  function drawSky() {
    const sky = $('#sky');
    const W = innerWidth;
    const H = innerHeight;
    const rnd = random(42);
    const sizes = [0.5, 0.6, 0.8, 1, 1.2];
    const alphas = [0.2, 0.3, 0.45, 0.6];
    let dots = '';
    for (let i = Math.round((W * H) / 4800); i > 0; i--) {
      const x = (rnd() * W).toFixed(0);
      const y = (rnd() * H).toFixed(0);
      dots += `<circle cx="${x}" cy="${y}" r="${sizes[Math.floor(rnd() * 5)]}" opacity="${alphas[Math.floor(rnd() * 4)]}"></circle>`;
    }
    sky.setAttribute('viewBox', `0 0 ${W} ${H}`);
    sky.innerHTML = `<g fill="#DDE2FF">${dots}</g>`;
  }
})();
